### ISSUE TITLE
feat: handle labels

### ISSUE THREAD

**Issue by TGTGamer** [cla-assistant/github-action#17]
Heya guys,

Should be a simple one for you to implement. I'd like to be able to label my pull requests once someone has signed the CLA. 

I currently have the following labels: 
CLA - Not Required (applied when specific conditions are met - done through workflow)
CLA - Signed
CLA - Unsigned

Part 1: I'd like to have an input for these labels to be automatically assigned when the bot runs. 
Part 2: I'd like the bot to automatically skip when specific labels are on the pull request

So the workflow.yml would look like this
```yml
jobs:
  CLAssistant:
  name: "CLA Assistant"
  runs-on: ubuntu-latest
  steps:
    - name: "CLA Assistant"
      if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request'
      # Alpha Release
      uses: cla-assistant/github-action@v1.3.0-alpha
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path-to-signatures: './contributors/cla.json'
        path-To-cladocument: 'https://github.com/${{github.repository}}/contributors/cla.md'
        # branch should not be protected
        branch: 'master'
        whitelist: ${{github.rerepository_owner}},bot*
        empty-commit-flag: false
        blockchain-storage-flag: false
        unsignedLabel: 'CLA - Unsigned'
        signedLabel: 'CLA - signed'
        ignoreLabel: 'CLA - Not Required'
```
