### ISSUE TITLE
[Bug] Skip CLA comment if already commented

### ISSUE THREAD

**Issue by AnandChowdhary** [cla-assistant/github-action#46]
If there's already a comment "All contributors have signed the CLA", and there's a new push, the comment is added again.

It can be skipped if the new push is from the same contributors who have already signed the CLA.

**Comment by ibakshay** [comment]
Hi @AnandChowdhary, 
Could you please post the screenshot or link to the Pull Request where multiple comments are added by the CLA GA bot in the same Pull Request? 
If this is the case, then it is a bug :/.

**Comment by AnandChowdhary** [comment]
![Screen Shot 2020-08-25 at 16 58 00](https://user-images.githubusercontent.com/2841780/91169008-33947f00-e6f4-11ea-9b55-74a1cf859ed6.png)

```yaml
name: CLA Assistant
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
jobs:
  claAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "Sign CLA"
        if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@master
# ...
```
