### ISSUE TITLE
[Feature] Trim spaces from signature comment

### ISSUE THREAD

**Issue by RobiNino** [cla-assistant/github-action#57]
**Is your feature request related to a problem? Please describe.**
When users copy the signing line into a comment ("'I have read the CLA Document..."), it is often copied with extra spaces or new lines. Since the action is comparing the comment's content strictly to the expected line, it is not recognized as a signing. We sometimes have to ask the users to try again multiple times until they get it right.

**Describe the solution you'd like**
It would be nice if the action would know to trim extra lines and spaces when comparing to the expected line. I know the comparison happens in my own workflow and that the solution should probably be there, but I'm reaching out to see maybe someone run into the same problem and has a solution.

**Describe alternatives you've considered**
1. Github Action offers a `contains()` function, but then it ignores extra words that might make the signing invalid.
2. Make the comparison inside the Action step itself and not in the workflow (would mean the step will run on every comment, which might be a waste)

**Comment by ibakshay** [comment]
Hi @RobiNino, Thank you very much for the write up. I see this issue too, However, at the moment,  I don't have any solution to counter tbh.  
>Make the comparison inside the Action step itself and not in the workflow (would mean the step will run on every comment, which might be a waste)

I also thought of handling this use case inside the action itself but then again like you have mentioned, I don't want to execute this action for every single issue comment. So, I dropped this idea. 

>Github Action offers a contains() function, but then it ignores extra words that might make the signing invalid.

Yes, extra wording will make the signing invalid. 


The optimum solution would be to do a comparison in the workflow file itself and we need to see If there is a way to trim the spaces. I will check it out this weekend and also if you find a solution then feel free to create a PR. I will be very happy to merge your contribution :).

**Comment by AndrewGable** [comment]
+1 - This would be great. We are running into this somewhat often in https://github.com/Expensify/Expensify.cash 

I'd be happy to provide a few examples if it is helpful!

**Comment by ibakshay** [comment]
Hi @RobiNino @andrei-panov, This issue is fixed by @yahavi in this PR https://github.com/cla-assistant/github-action/pull/69. Please update the CLA action workflow file  to the latest version `v2.0.3-alpha` so that this fix will be reflected :) . 

```yml
uses: cla-assistant/github-action@v2.0.3-alpha
```

**Comment by yahavi** [comment]
I would recommend using [action-regex-match](https://github.com/actions-ecosystem/action-regex-match) to better deal with newlines:
```yml
- uses: actions-ecosystem/action-regex-match@v2
id: sign
with:
    text: ${{ github.event.comment.body }}
    regex: '\s*I have read the CLA Document and I hereby sign the CLA\s*'

- uses: actions-ecosystem/action-regex-match@v2
id: recheck
with:
    text: ${{ github.event.comment.body }}
    regex: '\s*recheckcla\s*'

- name: "CLA Assistant"
uses: cla-assistant/github-action@v2.0.3-alpha
if: ${{ steps.recheck.outputs.match != '' || steps.sign.outputs.match != '' }} || github.event_name == 'pull_request_target'
# Now that #69 is merged, comment body with newlines won't be ignored in the cla-assistent
...
```
